
#include <stdio.h>
#include <openssl/rsa.h>
#include <openssl/pem.h>
#include <openssl/err.h>
#include <openssl/rand.h>
#include <string.h>

#define RSAKEYLEN 2048
#define PUBLICXPONENT 3

unsigned char key[256/8], IV[16];
RSA *keypair;
size_t priv_keylen;
size_t pub_keylen;
char *priv_key;
char *pub_key;
char *encryptedkey;
char *decryptedkey;

static void PrintinHex(const void* hexval , size_t length)
{
	const unsigned char * hexnum = (const unsigned char*)hexval;
	if (NULL == hexval)
        {
		printf("NULL");
	}
	else
	{
        	size_t it = 0;
        	for (; it<length; ++it)
            	{	printf("%02X ", *hexnum++);
    		}
	}
	printf("\n");
}

/*This function should not be generated by Bob. It is Alice's responsibilty. This is just for testing purposes.*/
void GenerateSymmetricKey()
{
	
	if(!RAND_bytes(key, sizeof(key)))
	{
		printf("Could not generate the key\n");
	}
	if(!RAND_bytes(IV, sizeof(IV)))
	{
		printf("Could not generate the IV\n");
	}

} 
void RSAKeyGenerator()
{	
	printf("\n.............Generating RSA KEY PAIR IA............\n");
	keypair = RSA_generate_key(RSAKEYLEN, PUBLICXPONENT, NULL, NULL);
	//BIO *priv = BIO_new(BIO_s_mem());
	//BIO *pub = BIO_new(BIO_s_mem());
	//PEM_write_bio_RSAPrivateKey(priv, keypair, NULL, NULL, 0, NULL, NULL);
	//PEM_write_bio_RSAPublicKey(priv, keypair);
	BIO *pub = BIO_new_file("public.pem", "w+");
    	PEM_write_bio_RSAPublicKey(pub, keypair);
	BIO *priv = BIO_new_file("private.pem", "w+");
    	PEM_write_bio_RSAPrivateKey(priv, keypair, NULL, NULL,0,NULL,NULL);
	
	priv_keylen = BIO_pending(priv);
	pub_keylen = BIO_pending(pub);
	priv_key = malloc(priv_keylen + 1);
	pub_key = malloc(pub_keylen + 1);
	BIO_read(priv, priv_key, priv_keylen);
	BIO_read(pub, pub_key, pub_keylen);
	priv_key[priv_keylen] = '\0';
	pub_key[pub_keylen] = '\0';
	printf("\n%s\n%s\n", priv_key, pub_key);
	
	//key[sizeof(key)-1] = '\0';
	encryptedkey = malloc(RSA_size(keypair));
	int enc = RSA_public_encrypt(32, key, (unsigned char *)encryptedkey, keypair, RSA_PKCS1_OAEP_PADDING);
	if (enc == -1)
	{
		perror("Error in encryption\n");
		RSA_free(keypair);
    		BIO_free_all(pub);
    		BIO_free_all(priv);
		free(priv_key);
		free(pub_key);
		free(encryptedkey);
		free(decryptedkey);
	}
	printf("The 256 bit AES key is \n");
	PrintinHex(key, sizeof(key));
	printf("size of encrypted text is %d\n", enc);
	printf("The encrypted text is \n");
	PrintinHex(encryptedkey, enc);
	
	decryptedkey = malloc(enc);
	int dec = RSA_private_decrypt(enc, (unsigned char *)encryptedkey, (unsigned char *)decryptedkey, keypair, RSA_PKCS1_OAEP_PADDING);
    	if(dec == -1)
	{
		perror("error in decryption\n");
		RSA_free(keypair);
    		BIO_free_all(pub);
    		BIO_free_all(priv);
		free(priv_key);
		free(pub_key);
		free(encryptedkey);
		free(decryptedkey);
	}
	printf("size of decr is %d\n", dec);
	printf("The decrypted key is \n");
	PrintinHex(decryptedkey, enc);
	//printf("the message is %#x\n", (unsigned char *)decryptedkey);
}
void main()
{
	encryptedkey = NULL;
	decryptedkey = NULL;
	OpenSSL_add_all_algorithms();
    	ERR_load_crypto_strings(); 
	GenerateSymmetricKey();
	RSAKeyGenerator();
		
}
